/*
   Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first
   ten pentagonal numbers are:

                  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

   It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
   difference, 70 − 22 = 48, is not pentagonal.

   Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
   and difference are pentagonal and D = |P[k] − P[j]| is minimised; what is
   the value of D?
 */

namespace pr44{
    bool isPent(int x){

        int num = 2 * x;
        for (int i = 1; i * i <= num; i++){
            if (i * (3*i - 1) == num){
                return true;
            }
        }
        return false;
    }

    int abs(int x){
        if (x < 0){return -x;}
        else return x;
    }

    int pent(int x){
        return x*(3*x-1)/2;
    }
}

int problem44() {
    int first, second;
    for (int sum = 3; sum < 100000; sum++){
        second = 1;
        first = sum - second;
        while (first > second){
            int d = pr44::pent(first) - pr44::pent(second);
            int s = pr44::pent(first) + pr44::pent(second);
            if (pr44::isPent(d) && pr44::isPent(s)){return d;}
            first--; second++;
        }
    }
    return -1;
}