/*
   The sequence of triangle numbers is generated by adding the natural
   numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
   28. The first ten terms would be:

                    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

   Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
     10: 1,2,5,10
     15: 1,3,5,15
     21: 1,3,7,21
     28: 1,2,4,7,14,28

   We can see that 28 is the first triangle number to have over five
   divisors.
   What is the value of the first triangle number to have over five hundred
   divisors?
*/

namespace pr12{
    int trDivisors(int n){
        int result = 0;
        for (int i = 1; i*i <= n; i++){
            if (n % i == 0) {result+=2;}
        }
        return result;
    }

    bool isSquare(int n){
        int i = 1;
        while (i*i < n){
            ++i;
        }
        if (i*i == n){return true;}
        else {return false;}
    }

    int divisors(int n){
        int result = 0;
        int i;
        for (i = 1; i*i < n; i++){
            if (n % i == 0) {result+=2;}
        }
        if (i*i == n) {result -= 1;}
        return result;
    }
}

long problem12() {
    int count = 1;
    while (true) {
        count++;
        if ( pr12::divisors(count/2) * pr12::divisors(count+1) > 500) {return count*(count+1)/2;}
        count++;
        if (pr12::divisors(count) * pr12::divisors((count+1)/2) > 500){return count*(count+1)/2;}
    }
}